plugins: [
  jekyll-paginate,
  jekyll-feed,
]

name: Tracer Codes
author: Tracer

environment: deveopment
url: http://localhost
baseurl: '/'

background_image: backgrounds/aquarium.jpg
cv_pdf: media/CV_EduardoP_EN_2020.pdf


# paginate settings
# Pagination Settings
paginate: 3
paginate_path: "/pages/blog/page:num"





# Server Config options
livereload: true