# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/t2ac32'}
- {icon: 'twitter', link: 'https://twitter.com/init_tracer'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/eduardopradomsc/'}
- {icon: 'instagram', link: 'https://www.instagram.com/t2ac32'}
- {icon: 'discord', link: 'https://discord.gg/uMt75X'}
